config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :youtube

  get '/auth/:provider/callback', to: 'sessions#create', as: :login
  get '/change_character/:character_id', to: 'sessions#pick', as: :pick
  get '/logout', to: 'sessions#logout', as: :logout

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boss.rb
class Boss < ApplicationRecord
  has_many :Npcs
  has_many :Youtubes
end

app/models/character.rb
class Character < ApplicationRecord
  class NoRank
    def position
      Character.count
    end

    def ilvl
      0
    end
  end

  has_many :youtubes
  validates :name, uniqueness: { scope: :realm }
  has_one :rank

  def ilvl_change
    ilvl - rank.ilvl
  end

  def rank
    super || NoRank.new
  end
end

app/models/npc.rb
class Npc < ApplicationRecord
  belongs_to :boss
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :character
  validates :character, presence: true, uniqueness: true
  validates :ilvl, :position, presence: true
end

app/models/youtube.rb
class Youtube < ApplicationRecord
  belongs_to :boss
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
require 'bnet_api'

class SessionsController < ApplicationController
  def create
    token = request.env['omniauth.auth']['credentials']['token']
    token = ENV['BNET_TOKEN'] unless Rails.env.production?
    session[:current_character_id] = 1 unless Rails.env.production?
    return redirect_to '/' unless Rails.env.production?
    session[:bnet_token] = token
    @characters = Array.new
    bnet = Battlenet.new(locale: "en_us", api_key: Rails.application.credentials.bnet[:api_key])
    users_characters = bnet.characters(access_token: token)
    users_characters['characters'].each do | character |
      if character.fetch('guild', nil) == Rails.configuration.wow['guild'] &&
         character.fetch('realm') == Rails.configuration.wow['realm']
        c = Character.find_or_create_by(name: character['name'],
                                        realm: character['realm'])
        c.update(portrait: bnet.character_image(character: character),
                 level: character['level'])
        @characters.push(c)
      end
    end
  end

  def pick
    @character = Character.find(params[:character_id])
    session[:current_character_id] = @character.id
    redirect_to '/'
  end

  def logout
    session[:current_character_id] = nil
    session[:bnet_token] = nil
    redirect_to '/'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @character = Character.find(session[:current_character_id]) unless session[:current_character_id] == nil
    max_level = Character.maximum(:level)
    @characters = Character.where(level: max_level).order(ilvl: :desc)
    @youtubes = Youtube.all.order(created_at: :desc)
    @patch = Boss.where.not(patch: nil).order(patch: :desc).first.patch
    @bosses = Boss.where(patch: @patch)
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  def new
    @character = Character.find(session[:current_character_id]) unless session[:current_character_id] == nil
  end

  def create
    Youtube.create(youtube_params)
    redirect_to '/'
  end

  private
    def youtube_params
      params.require(:youtube).permit(:link, :character_id, :boss_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rgoat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="header" style="background-image:url('https://goats.space/static/headers/header<%= rand(1..17) %>.jpg')">
    <%= link_to 'Space Goats', welcome_index_path %>
  </div>

  <div class="sidebar">
    <div class="login_info">
      <% if session[:current_character_id] %>
      <div class="logged_in_portrait">
        <h2><%= @character.name %></h2>
        <img class="login_portrait" src="<%= @character.portrait %>">
      </div>
      <div class="login_buttons">
        <%= link_to 'New Video', new_youtube_path, { :class => "new_video_button"} %>
        <%= link_to 'Logout', logout_path, { :class => "logout_button" } %>
      </div>
      <% else %>
      <div class="login_buttons">
        <%= link_to 'Login', '/auth/bnet', { :class => "new_video_button" } %>
      </div>
      <% end %>
    </div>

    <div class="character_roster">
      <h3 class="guild_name">&lt;<%= Rails.configuration.wow['guild'] %>&gt;</h3>
      <div class="roster_table">
      <% @characters.each_with_index do | character, index | %>
        <div class="roster_character <%= character.class_name %>">
          <span class="character_name"><%= character.name %></span>
          <span class="character_ilvl">
            <%= character.ilvl %>
            <% if character.ilvl != character.rank.ilvl %>
            (+<%= character.ilvl - character.rank.ilvl %>)
            <% end %>
            <% if index > character.rank.position %>
            ▼<%= index - character.rank.position %>
            <% elsif index < character.rank.position %>
            ▲<%= character.rank.position - index %>
            <% end %>
          </span>
          <a class="character_portrait" href="https://worldofwarcraft.com/en-us/character/<%= character.realm %>/<%= character.name %>"><img src="<%= character.portrait %>"></a>
        </div>
      <% end %>
      </div>
    </div>

    <div class="current_bosses">
      <h3>Patch <%= @patch %></h3>
      <table>
      <% @bosses.each do | boss | %>
        <tr>
          <td><%= boss.name %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>

  <div class="main-content">
  <% @youtubes.each do | youtube | %>
    <div class="video">
      <a class="video_link" href="https://www.youtube.com/watch?v=<%=youtube.link%>">
        <div class="thumbnail" style="background-image:url('https://img.youtube.com/vi/<%=youtube.link%>/sddefault.jpg')">
            <img class="play_button" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/YouTube_light_logo_%282017%29.svg/512px-YouTube_light_logo_%282017%29.svg.png">
            <h1 class="description"><%=youtube.boss.name%></h1>
            <span class="description">[<%=youtube.character.name%>]</span>
        </div>
      </a>
    </div>
  <% end %>
  </div>
</div>

app/views/youtube/new.html.erb
Upload a new video

<%= form_with scope: :youtube, url: youtube_index_path, local: true do |form| %>
  <%= form.hidden_field(:character_id, :value => @character.id) %>
  <p>
    <%= form.label :link %><br>
    <%= form.text_field :link %>
  </p>
  <p>
    <%= collection_select(:youtube, :boss_id,
                          Boss.where.not(patch: nil).order(patch: :desc),
                          :id, :name,
                          {include_blank: 'None'}) %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>